"""Comic Agent — end-to-end AIGC short video production pipeline.

Input: "帮我做一个关于猫娘的30秒短视频"
Pipeline:
  1. Script Writing (LLM)     → scenes with narration + visual prompts
  2. Image Generation (ComfyUI) → one image per scene
  3. Voiceover (TTS)          → one audio per scene
  4. Video Assembly (ffmpeg)  → final MP4

Output: comic_output/{timestamp}/output.mp4 + intermediates
"""

import json
import os
import time
import uuid
import shutil
from dataclasses import dataclass, field
from typing import Any

from ..config import LLAMA_API, MODEL_LLAMA
from ..pipeline.tracing import TraceCollector


# ─── Data types ───

@dataclass
class Scene:
    """A single scene in the storyboard."""
    index: int
    narration: str           # voiceover text (Chinese)
    visual_prompt: str       # ComfyUI image prompt (English for better quality)
    duration_s: float = 5.0  # default 5 seconds per scene
    image_path: str = ""
    audio_path: str = ""


@dataclass
class ComicScript:
    """Full storyboard generated by LLM."""
    title: str
    style: str               # art style (e.g., "anime", "Production IG")
    character_desc: str      # main character description
    scenes: list[Scene] = field(default_factory=list)

    @property
    def total_duration(self) -> float:
        return sum(s.duration_s for s in self.scenes)


@dataclass
class ComicResult:
    """Complete comic production result."""
    task_id: str
    output_dir: str
    video_path: str
    script: ComicScript | None = None
    total_duration_s: float = 0
    errors: list[str] = field(default_factory=list)


# ─── LLM script generation ───

_SCRIPT_SYSTEM_PROMPT = """You are an anime storyboard director. Given a user's request, create a short video storyboard.

Output JSON format:
{
  "title": "视频标题",
  "style": "画风 (anime/ghibli/Production IG/cyberpunk/etc.)",
  "character_desc": "主角外观描述（用于保持角色一致性）",
  "scenes": [
    {
      "index": 1,
      "narration": "旁白/台词（中文，15-30字）",
      "visual_prompt": "英文画面描述 (50-100 words, include character description, background, lighting, camera angle)",
      "duration_s": 5
    }
  ]
}

Rules:
- 30-second video = 5-6 scenes, each ~5 seconds
- narration should be natural Chinese speech, not too formal
- visual_prompt MUST be in English (for Stable Diffusion), detailed enough for image generation
- Include the main character in every scene (for consistency)
- Add "anime style, high quality, masterpiece" to every visual_prompt
- Duration per scene: 4-7 seconds

Output ONLY the JSON, no other text."""


def generate_script(user_prompt: str, scene_count: int = 6) -> ComicScript:
    """Generate storyboard using LLM."""
    import requests as req_lib

    user_msg = (
        f"Create a {scene_count * 5}-second anime short video storyboard.\n"
        f"User request: {user_prompt}\n\n"
        f"Generate {scene_count} scenes, each ~5 seconds."
    )

    payload = {
        "model": MODEL_LLAMA,
        "messages": [
            {"role": "system", "content": _SCRIPT_SYSTEM_PROMPT},
            {"role": "user", "content": user_msg},
        ],
        "max_tokens": 2048,
        "temperature": 0.8,
        "stream": False,
        "thinking": {"type": "disabled"},
    }

    try:
        resp = req_lib.post(LLAMA_API, json=payload, timeout=300)
        if resp.status_code == 200:
            msg = resp.json()["choices"][0]["message"]
            raw = msg.get("content", "") or msg.get("reasoning_content", "")[-500:] or ""
        else:
            raw = ""
    except Exception:
        raw = ""

    # Parse JSON
    try:
        raw = raw.strip().strip("`").replace("json\n", "").strip()
        data = json.loads(raw)
    except json.JSONDecodeError:
        # Fallback: create a simple script
        data = {
            "title": "AI Generated Short",
            "style": "anime",
            "character_desc": "anime character",
            "scenes": [
                {
                    "index": i + 1,
                    "narration": f"场景 {i + 1}",
                    "visual_prompt": f"anime style, high quality, masterpiece, {user_prompt}",
                    "duration_s": 5,
                }
                for i in range(scene_count)
            ],
        }

    scenes = [
        Scene(
            index=s["index"],
            narration=s.get("narration", ""),
            visual_prompt=s.get("visual_prompt", ""),
            duration_s=float(s.get("duration_s", 5)),
        )
        for s in data.get("scenes", [])
    ]

    return ComicScript(
        title=data.get("title", "Untitled"),
        style=data.get("style", "anime"),
        character_desc=data.get("character_desc", ""),
        scenes=scenes,
    )


# ─── Image generation ───

def generate_scene_image(scene: Scene, output_dir: str,
                         character_ref: str = "") -> str:
    """Generate one scene image via ComfyUI."""
    from ..tools.comfyui import _tool_comfyui_text2img

    prompt = scene.visual_prompt
    if character_ref:
        prompt = f"{character_ref}, {prompt}"

    # Add quality tags
    if "masterpiece" not in prompt.lower():
        prompt += ", masterpiece, best quality"

    print(f"  🎨 Scene {scene.index}: generating image...")

    try:
        result = _tool_comfyui_text2img(prompt=prompt, retries=2)
        # Result is JSON string with output path
        try:
            data = json.loads(result)
            image_path = data.get("output", data.get("path", ""))
        except (json.JSONDecodeError, TypeError):
            image_path = str(result)

        if image_path and os.path.exists(image_path):
            # Copy to output dir
            ext = os.path.splitext(image_path)[1] or ".png"
            dest = os.path.join(output_dir, f"scene_{scene.index:02d}{ext}")
            shutil.copy2(image_path, dest)
            print(f"  ✅ Scene {scene.index}: {dest}")
            return dest
    except Exception as e:
        print(f"  ❌ Scene {scene.index}: {e}")

    # Fallback: create a placeholder
    placeholder = os.path.join(output_dir, f"scene_{scene.index:02d}.txt")
    with open(placeholder, "w", encoding="utf-8") as f:
        f.write(f"Scene {scene.index}\nPrompt: {prompt}\n")
    return placeholder


def generate_all_images(script: ComicScript, output_dir: str,
                        character_ref: str = "") -> dict[int, str]:
    """Generate images for all scenes."""
    results = {}
    for scene in script.scenes:
        path = generate_scene_image(scene, output_dir, character_ref)
        scene.image_path = path
        results[scene.index] = path
    return results


# ─── Voiceover generation ───

def generate_scene_audio(scene: Scene, output_dir: str) -> str:
    """Generate TTS audio for a scene using edge-tts (free, no API key).

    Falls back to silent audio if edge-tts not available.
    """
    text = scene.narration
    if not text:
        text = "..."

    audio_path = os.path.join(output_dir, f"audio_{scene.index:02d}.mp3")

    # Try edge-tts first (free, high quality Chinese TTS)
    try:
        import subprocess
        import sys
        result = subprocess.run(
            [
                sys.executable, "-m", "edge_tts",
                "--voice", "zh-CN-XiaoxiaoNeural",
                "--text", text,
                "--write-media", audio_path,
            ],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0 and os.path.exists(audio_path):
            print(f"  🔊 Scene {scene.index}: TTS OK ({os.path.getsize(audio_path)} bytes)")
            return audio_path
    except Exception as e:
        print(f"  ⚠ edge-tts failed: {e}")

    # Fallback: generate silent audio via ffmpeg
    try:
        import subprocess
        dur = scene.duration_s
        subprocess.run([
            "ffmpeg", "-y", "-f", "lavfi",
            "-i", f"anullsrc=r=24000:cl=mono",
            "-t", str(dur),
            audio_path,
        ], capture_output=True, timeout=10)
        print(f"  🔇 Scene {scene.index}: silent audio ({dur}s)")
        return audio_path
    except Exception:
        pass

    return ""


def generate_all_audio(script: ComicScript, output_dir: str) -> dict[int, str]:
    """Generate voiceover for all scenes."""
    results = {}
    for scene in script.scenes:
        path = generate_scene_audio(scene, output_dir)
        scene.audio_path = path
        results[scene.index] = path
    return results


# ─── Video assembly ───

def assemble_video(script: ComicScript, output_dir: str,
                   output_path: str = "",
                   fps: int = 24) -> str:
    """Assemble scenes into final MP4 video using ffmpeg."""
    if not output_path:
        output_path = os.path.join(output_dir, "output.mp4")

    import subprocess

    # Build ffmpeg concat input
    concat_file = os.path.join(output_dir, "concat.txt")
    filter_complex_parts = []
    input_args = []

    valid_scenes = []
    for s in script.scenes:
        if s.image_path and os.path.exists(s.image_path) and not s.image_path.endswith(".txt"):
            valid_scenes.append(s)

    if not valid_scenes:
        print("⚠ No valid scenes to assemble")
        return ""

    with open(concat_file, "w", encoding="utf-8") as f:
        for i, s in enumerate(valid_scenes):
            # Video input (image → video stream)
            input_args.extend([
                "-loop", "1", "-t", str(s.duration_s),
                "-i", s.image_path,
            ])
            # Audio input
            if s.audio_path and os.path.exists(s.audio_path):
                input_args.extend([
                    "-t", str(s.duration_s),
                    "-i", s.audio_path,
                ])
            else:
                # Silent audio
                input_args.extend([
                    "-f", "lavfi", "-t", str(s.duration_s),
                    "-i", f"anullsrc=r=24000:cl=mono",
                ])

            # Filter: image → video with zoom effect
            vid_idx = i * 2       # video input index
            filter_complex_parts.append(
                f"[{vid_idx}:v]fps={fps},scale=1280:720:force_original_aspect_ratio=decrease,"
                f"pad=1280:720:(ow-iw)/2:(oh-ih)/2,"
                f"zoompan=z='min(zoom+0.001,1.1)':d={int(s.duration_s * fps)}:s=1280x720,"
                f"format=yuv420p[v{i}]"
            )
            aud_idx = vid_idx + 1  # audio input index
            filter_complex_parts.append(f"[{aud_idx}:a]aformat=sample_rates=24000[a{i}]")

    # Concat all scenes
    v_inputs = "".join(f"[v{i}]" for i in range(len(valid_scenes)))
    a_inputs = "".join(f"[a{i}]" for i in range(len(valid_scenes)))
    filter_complex_parts.append(
        f"{v_inputs}concat=n={len(valid_scenes)}:v=1:a=0[outv];"
        f"{a_inputs}concat=n={len(valid_scenes)}:v=0:a=1[outa]"
    )

    filter_complex = ";".join(filter_complex_parts)

    cmd = [
        "ffmpeg", "-y",
    ] + input_args + [
        "-filter_complex", filter_complex,
        "-map", "[outv]", "-map", "[outa]",
        "-c:v", "libx264", "-preset", "fast", "-crf", "23",
        "-c:a", "aac", "-b:a", "128k",
        "-shortest",
        output_path,
    ]

    print(f"  🎬 Assembling video ({len(valid_scenes)} scenes)...")
    try:
        subprocess.run(cmd, capture_output=True, timeout=300, check=True)
        size_mb = os.path.getsize(output_path) / (1024 * 1024)
        print(f"  ✅ Video: {output_path} ({size_mb:.1f} MB)")
        return output_path
    except subprocess.CalledProcessError as e:
        print(f"  ❌ ffmpeg failed: {e.stderr.decode()[:200] if e.stderr else e}")
        return ""


# ─── Main Comic Agent ───

def produce_comic(
    user_prompt: str,
    scene_count: int = 6,
    output_base: str = "",
    enable_images: bool = True,
    enable_audio: bool = True,
    character_ref: str = "",
) -> ComicResult:
    """End-to-end comic/short video production.

    Args:
        user_prompt: Natural language description (e.g., "猫娘在咖啡馆打工的一天")
        scene_count: Number of scenes (default 6 for ~30s)
        output_base: Base output directory (default: comic_output/{timestamp}/)
        enable_images: Generate images via ComfyUI
        enable_audio: Generate voiceover via TTS
        character_ref: Reference character description for consistency

    Returns:
        ComicResult with video path and metadata
    """
    task_id = str(uuid.uuid4())[:8]
    ts = time.strftime("%Y%m%d_%H%M%S")

    if not output_base:
        output_base = os.path.join(os.getcwd(), "comic_output", f"{ts}_{task_id}")

    os.makedirs(output_base, exist_ok=True)

    print(f"\n{'='*60}")
    print(f"🎬 Comic Agent: {user_prompt[:80]}")
    print(f"📁 Output: {output_base}")
    print(f"{'='*60}")

    errors: list[str] = []

    # Step 1: Script generation
    print("\n📝 Step 1/4: Generating script...")
    t0 = time.time()
    try:
        script = generate_script(user_prompt, scene_count)
        print(f"  Title: {script.title}")
        print(f"  Style: {script.style}")
        print(f"  Scenes: {len(script.scenes)} ({script.total_duration:.0f}s)")
        # Save script
        script_path = os.path.join(output_base, "script.json")
        with open(script_path, "w", encoding="utf-8") as f:
            json.dump({
                "title": script.title,
                "style": script.style,
                "character_desc": script.character_desc,
                "scenes": [
                    {
                        "index": s.index,
                        "narration": s.narration,
                        "visual_prompt": s.visual_prompt,
                        "duration_s": s.duration_s,
                    }
                    for s in script.scenes
                ],
            }, f, ensure_ascii=False, indent=2)
        print(f"  Script saved: {script_path}")
    except Exception as e:
        errors.append(f"script: {e}")
        return ComicResult(task_id=task_id, output_dir=output_base,
                           video_path="", errors=errors)
    print(f"  ⏱ {time.time() - t0:.1f}s")

    # Step 2: Image generation
    if enable_images:
        print("\n🎨 Step 2/4: Generating images...")
        t0 = time.time()
        try:
            generate_all_images(script, output_base,
                                character_ref or script.character_desc)
        except Exception as e:
            errors.append(f"images: {e}")
            print(f"  ❌ Image generation failed: {e}")
        print(f"  ⏱ {time.time() - t0:.1f}s")

    # Step 3: Voiceover
    if enable_audio:
        print("\n🔊 Step 3/4: Generating voiceover...")
        t0 = time.time()
        try:
            generate_all_audio(script, output_base)
        except Exception as e:
            errors.append(f"audio: {e}")
            print(f"  ❌ Audio generation failed: {e}")
        print(f"  ⏱ {time.time() - t0:.1f}s")

    # Step 4: Video assembly
    print("\n🎬 Step 4/4: Assembling video...")
    t0 = time.time()
    video_path = ""
    try:
        video_path = assemble_video(script, output_base)
    except Exception as e:
        errors.append(f"assemble: {e}")
        print(f"  ❌ Assembly failed: {e}")
    print(f"  ⏱ {time.time() - t0:.1f}s")

    print(f"\n{'='*60}")
    if video_path:
        print(f"✅ Done! Video: {video_path}")
    else:
        print(f"⚠ Partial: check {output_base}")
        print(f"Errors: {errors}")
    print(f"{'='*60}")

    return ComicResult(
        task_id=task_id,
        output_dir=output_base,
        video_path=video_path,
        script=script,
        total_duration_s=script.total_duration,
        errors=errors,
    )
